import './modules/application.js'
import './modules/gp_gencat_departments_controller.js'
import './modules/gp_gencat_interest_groups_controller.js'
import './modules/gp_gencat_welcome_controller.js'
import './modules/gp_gencat_common_controller.js'
import './modules/gp_gencat_map_controller.js'
